# Simple linting github action
name: Format and Checkin using Black

on: [push]
permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run black and format the code
        uses: psf/black@stable
        with:
          options: "--verbose"
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
        
