name: Python license check action

on:
  push:
    branches:
      - main

env:
  DEP_PATH: python/requirements.txt

jobs:
  validate-license:
    runs-on: ubuntu-latest
    steps:
      - name: Check out master
        uses: actions/checkout@master

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "python/requirements.txt"

      - name: License Checker
        uses: andersy005/gh-action-py-liccheck@main
        with:
          strategy-ini-file: ./python/license-conf.ini
          level: standard
          requirements-txt-file: ./python/requirements.txt
